packages:
  - apps/*
  - packages/*

overrides:
  '@opentelemetry/core': 2.8.0
  '@opentelemetry/propagator-jaeger': 2.9.0
  fast-uri@^3.0.0: 3.1.8
  fast-uri@^4.0.0: 4.1.5
  js-yaml: 4.3.2
  protobufjs: 8.6.6

allowBuilds:
  argon2: true
  electron: true
  electron-winstaller: true
  esbuild: true
  protobufjs: false
