import {
  ToolDefinitionSchema,
  type ApprovalRequirement,
  type Capability,
  type RiskLevel,
  type ToolDefinition,
} from "@alexa-control/shared";

const defineTool = (
  name: string,
  riskLevel: RiskLevel,
  approvalRequirement: ApprovalRequirement,
  requiredCapabilities: Capability[],
  targetType: ToolDefinition["targetType"] = "none",
  enabled = true,
  requiresTrustedDevice = false,
) =>
  ToolDefinitionSchema.parse({
    name,
    description: `Non-executable governance metadata for ${name}.`,
    inputSchemaId: `${name}.input.v1`,
    outputSchemaId: `${name}.output.v1`,
    riskLevel,
    requiredCapabilities,
    approvalRequirement,
    targetType,
    requiresTrustedDevice,
    timeoutMs: 5_000,
    supportsCancellation:
      enabled &&
      [
        "workspace.inspect_metadata",
        "workspace.read_file",
        "git.status",
        "git.diff",
        "git.current_branch",
        "repository.scan_metadata",
        "workspace.apply_patch",
        "workspace.validate_profile",
      ].includes(name),
    supportsDryRun: true,
    enabled,
    version: "1",
  });

export const BUILT_IN_TOOLS: ToolDefinition[] = [
  defineTool("ai.economic_override", "high", "recent_authentication", []),
  defineTool("security.view", "read_only", "none", ["security.view"]),
  defineTool("audit.list", "read_only", "none", ["security.view"]),
  defineTool("devices.list", "read_only", "none", ["security.view"]),
  defineTool("applications.list", "read_only", "none", ["security.view"]),
  defineTool("workspaces.list", "read_only", "none", ["security.view"]),
  defineTool("tools.list", "read_only", "none", ["security.view"]),
  defineTool("policy.evaluate", "read_only", "none", ["security.view"]),
  defineTool("approvals.list", "read_only", "none", ["security.view"]),
  defineTool(
    "git.status",
    "read_only",
    "session",
    ["git.status"],
    "workspace",
    true,
    true,
  ),
  defineTool("git.diff", "read_only", "session", ["git.diff"], "workspace", true, true),
  defineTool(
    "git.current_branch",
    "read_only",
    "session",
    ["git.status"],
    "workspace",
    true,
    true,
  ),
  defineTool(
    "workspace.inspect_metadata",
    "read_only",
    "session",
    ["workspace.read"],
    "workspace",
    true,
    true,
  ),
  defineTool(
    "workspace.read_file",
    "read_only",
    "session",
    ["workspace.read"],
    "workspace",
    true,
    true,
  ),
  defineTool(
    "repository.scan_metadata",
    "read_only",
    "session",
    ["workspace.read", "repository.index"],
    "workspace",
    true,
    true,
  ),
  defineTool(
    "workspace.apply_patch",
    "medium",
    "explicit",
    ["workspace.write", "workspace.modify_file"],
    "workspace",
    true,
    true,
  ),
  defineTool(
    "workspace.validate_profile",
    "medium",
    "explicit",
    ["workspace.read", "workspace.validate"],
    "workspace",
    true,
    true,
  ),
  defineTool("app.open", "low", "session", ["app.open"], "application", true, true),
  defineTool("app.focus", "low", "session", ["app.focus"], "application", true, true),
  defineTool(
    "browser.navigate",
    "low",
    "session",
    ["browser.navigate"],
    "application",
    true,
    true,
  ),
  defineTool(
    "browser.read_page",
    "read_only",
    "session",
    ["browser.read_page"],
    "application",
    true,
    true,
  ),
  defineTool(
    "browser.interact",
    "medium",
    "explicit",
    ["browser.interact"],
    "application",
    true,
    true,
  ),
  defineTool("governance.update_registry", "medium", "explicit", ["security.modify"]),
  defineTool(
    "workspace.create_file",
    "medium",
    "explicit",
    ["workspace.create_file"],
    "workspace",
    false,
    true,
  ),
  defineTool(
    "workspace.modify_file",
    "medium",
    "explicit",
    ["workspace.modify_file"],
    "workspace",
    false,
    true,
  ),
  defineTool(
    "project.run_registered_script",
    "medium",
    "explicit",
    ["terminal.run_registered_script"],
    "workspace",
    false,
    true,
  ),
  defineTool(
    "codex.start_write",
    "medium",
    "explicit",
    ["codex.start_write"],
    "workspace",
    false,
    true,
  ),
  defineTool(
    "git.commit",
    "high",
    "recent_authentication",
    ["git.commit"],
    "workspace",
    false,
    true,
  ),
  defineTool(
    "git.push",
    "high",
    "recent_authentication",
    ["git.push"],
    "workspace",
    false,
    true,
  ),
  defineTool(
    "email.send",
    "high",
    "recent_authentication",
    ["email.send"],
    "none",
    false,
    true,
  ),
  defineTool(
    "browser.submit_form",
    "high",
    "recent_authentication",
    ["browser.interact"],
    "application",
    true,
    true,
  ),
  // This is deliberately narrower than browser.submit_form: it covers the
  // reviewed composer controls in the registered ChatGPT and Codex apps only.
  // Other browser form submissions still require recent authentication.
  defineTool(
    "application.submit_ai_composer",
    "medium",
    "explicit",
    ["browser.interact"],
    "application",
    true,
    true,
  ),
  defineTool(
    "deployment.start",
    "high",
    "recent_authentication",
    ["terminal.run_registered_command"],
    "workspace",
    false,
    true,
  ),
  defineTool("security.modify", "high", "recent_authentication", ["security.modify"]),
  defineTool("device.revoke", "high", "recent_authentication", ["device.revoke"]),
  defineTool(
    "shell.execute_arbitrary",
    "prohibited",
    "prohibited",
    ["shell.execute_arbitrary"],
    "none",
    false,
    true,
  ),
  defineTool(
    "filesystem.read_arbitrary",
    "prohibited",
    "prohibited",
    ["filesystem.read_arbitrary"],
    "none",
    false,
    true,
  ),
  defineTool(
    "filesystem.delete_permanently",
    "prohibited",
    "prohibited",
    ["filesystem.delete_permanently"],
    "none",
    false,
    true,
  ),
  defineTool(
    "system.run_sudo",
    "prohibited",
    "prohibited",
    ["system.run_sudo"],
    "none",
    false,
    true,
  ),
  defineTool(
    "credentials.read",
    "prohibited",
    "prohibited",
    ["credentials.read"],
    "none",
    false,
    true,
  ),
  defineTool(
    "keychain.read",
    "prohibited",
    "prohibited",
    ["keychain.read"],
    "none",
    false,
    true,
  ),
  defineTool(
    "banking.perform_action",
    "prohibited",
    "prohibited",
    ["banking.perform_action"],
    "none",
    false,
    true,
  ),
  defineTool(
    "security.disable_controls",
    "prohibited",
    "prohibited",
    ["security.disable_controls"],
    "none",
    false,
    true,
  ),
];
