import { z } from "zod";
import type { BusinessActionRequest,BusinessProvider } from "@alexa-control/shared";
import type { AccountingProvider,AdsProvider,AnalyticsProvider,BusinessProviderExecutionContext,BusinessProviderResult,CommerceProvider } from "./business-providers.js";

const JsonObjectSchema=z.record(z.string(),z.unknown());type Fetcher=typeof fetch;
class ProviderHttpError extends Error{constructor(readonly kind:NonNullable<BusinessProviderResult["failureKind"]>,readonly retryable:boolean){super(kind);}}
const failure=(error:unknown,name:string):BusinessProviderResult=>{const value=error instanceof ProviderHttpError?error:new ProviderHttpError("INVALID_RECORD",false);return {outcome:"FAILED",externalReferenceId:null,summary:`${name} rejected the bounded read (${value.kind}).`,failureKind:value.kind,retryable:value.retryable};};
const bearer=async(fetcher:Fetcher,url:string,token:string,init:RequestInit={},headers:Record<string,string>={})=>{let response:Response;try{response=await fetcher(url,{...init,headers:{authorization:`Bearer ${token}`,"content-type":"application/json",...headers,...init.headers},signal:AbortSignal.timeout(10_000)});}catch(error){if(error instanceof Error&&error.name==="TimeoutError")throw new ProviderHttpError("TIMEOUT",true);throw new ProviderHttpError("OUTAGE",true);}if(!response.ok){if(response.status===401)throw new ProviderHttpError("EXPIRED_CREDENTIAL",false);if(response.status===403)throw new ProviderHttpError("PERMISSION_DENIED",false);if(response.status===429)throw new ProviderHttpError("RATE_LIMIT",true);if(response.status>=500)throw new ProviderHttpError("OUTAGE",true);throw new ProviderHttpError("INVALID_RECORD",false);}return JsonObjectSchema.parse(await response.json());};
const result=(name:string,reference:string|null):BusinessProviderResult=>({outcome:"VERIFIED",externalReferenceId:reference,summary:`${name} returned validated provider state for the bounded read.`});
const token=(context:BusinessProviderExecutionContext|undefined)=>{if(!context?.credential?.accessToken)throw new ProviderHttpError("EXPIRED_CREDENTIAL",false);return context.credential.accessToken;};
abstract class ReadProviderBase{readonly supportsIdempotentWrites=false;readonly requiresCredential=true;abstract readonly providerId:BusinessProvider;abstract readonly capabilities:ReadonlySet<BusinessActionRequest["capability"]>;health(context?:BusinessProviderExecutionContext){return Promise.resolve(context?.credential?.accessToken?{state:"HEALTHY" as const,reasonCode:"REVIEWED_OAUTH_READY",rateLimitRemaining:null}:{state:"REAUTH_REQUIRED" as const,reasonCode:"REVIEWED_OAUTH_REQUIRED",rateLimitRemaining:null});}reconcile(reference:string){return Promise.resolve({outcome:"FAILED" as const,externalReferenceId:reference,summary:"This representative adapter exposes read-only capabilities; reconciliation is not applicable.",failureKind:"INVALID_RECORD" as const,retryable:false});}}

export class XeroSandboxAccountingProvider extends ReadProviderBase implements AccountingProvider{
  readonly providerId="accounting" as const;readonly capabilities=new Set<BusinessActionRequest["capability"]>(["accounting.list_accounts","accounting.read_account","accounting.search_transactions","accounting.read_transaction","accounting.list_invoices","accounting.read_invoice","accounting.read_pnl","accounting.read_balance_sheet","accounting.read_cashflow"]);constructor(readonly fetcher:Fetcher=fetch){super();}
  async execute(action:BusinessActionRequest,context?:BusinessProviderExecutionContext){if(!this.capabilities.has(action.capability))return failure(new ProviderHttpError("PERMISSION_DENIED",false),"Xero sandbox");try{const credential=context?.credential;if(!credential?.tenantId)throw new ProviderHttpError("EXPIRED_CREDENTIAL",false);let path="/api.xro/2.0/Accounts";const id="externalResourceId" in action?action.externalResourceId:null;if(action.capability==="accounting.read_account")path=`/api.xro/2.0/Accounts/${encodeURIComponent(id!)}`;else if(action.capability==="accounting.search_transactions"||action.capability==="accounting.read_transaction")path=id?`/api.xro/2.0/BankTransactions/${encodeURIComponent(id)}`:"/api.xro/2.0/BankTransactions?page=1";else if(action.capability==="accounting.list_invoices"||action.capability==="accounting.read_invoice")path=id?`/api.xro/2.0/Invoices/${encodeURIComponent(id)}`:"/api.xro/2.0/Invoices?page=1";else if(action.capability==="accounting.read_pnl"||action.capability==="accounting.read_balance_sheet"||action.capability==="accounting.read_cashflow"){if(!("periodStart" in action)||!action.periodStart||!action.periodEnd)throw new ProviderHttpError("INVALID_RECORD",false);const report=action.capability==="accounting.read_pnl"?"ProfitAndLoss":action.capability==="accounting.read_balance_sheet"?"BalanceSheet":"CashSummary";path=`/api.xro/2.0/Reports/${report}?fromDate=${encodeURIComponent(action.periodStart.slice(0,10))}&toDate=${encodeURIComponent(action.periodEnd.slice(0,10))}`;}await bearer(this.fetcher,`https://api.xero.com${path}`,token(context),{}, {"xero-tenant-id":credential.tenantId});return result("Xero sandbox",id?`xero:${id}`:null);}catch(error){return failure(error,"Xero sandbox");}}
}

export class GoogleAdsTestProvider extends ReadProviderBase implements AdsProvider{
  readonly providerId="ads" as const;readonly capabilities=new Set<BusinessActionRequest["capability"]>(["ads.list_campaigns","ads.read_campaign","ads.read_performance","ads.read_spend","ads.read_conversions"]);constructor(readonly fetcher:Fetcher=fetch){super();}
  async execute(action:BusinessActionRequest,context?:BusinessProviderExecutionContext){if(!this.capabilities.has(action.capability))return failure(new ProviderHttpError("PERMISSION_DENIED",false),"Google Ads test account");try{const credential=context?.credential;if(!credential?.developerToken||!credential.customerId)throw new ProviderHttpError("EXPIRED_CREDENTIAL",false);const id="externalResourceId" in action?action.externalResourceId:null,where=id?` WHERE campaign.id = ${Number(id)}`:"",query=`SELECT campaign.id, campaign.name, campaign.status, metrics.cost_micros, metrics.conversions FROM campaign${where} LIMIT ${"limit" in action?action.limit:25}`;await bearer(this.fetcher,`https://googleads.googleapis.com/v19/customers/${credential.customerId}/googleAds:searchStream`,token(context),{method:"POST",body:JSON.stringify({query})},{"developer-token":credential.developerToken});return result("Google Ads test account",id?`google-ads:${id}`:null);}catch(error){return failure(error,"Google Ads test account");}}
}

export class GoogleAnalytics4Provider extends ReadProviderBase implements AnalyticsProvider{
  readonly providerId="analytics" as const;readonly capabilities=new Set<BusinessActionRequest["capability"]>(["analytics.query_metric","analytics.query_timeseries","analytics.query_conversions","analytics.query_channel_performance"]);constructor(readonly fetcher:Fetcher=fetch){super();}
  async execute(action:BusinessActionRequest,context?:BusinessProviderExecutionContext){if(!this.capabilities.has(action.capability)||!("metricId" in action)||!("periodStart" in action)||!action.metricId||!action.periodStart||!action.periodEnd)return failure(new ProviderHttpError("PERMISSION_DENIED",false),"Google Analytics 4");try{const propertyId=context?.credential?.propertyId;if(!propertyId)throw new ProviderHttpError("EXPIRED_CREDENTIAL",false);await bearer(this.fetcher,`https://analyticsdata.googleapis.com/v1beta/properties/${propertyId}:runReport`,token(context),{method:"POST",body:JSON.stringify({dateRanges:[{startDate:action.periodStart.slice(0,10),endDate:action.periodEnd.slice(0,10)}],metrics:[{name:action.metricId}],dimensions:action.dimensions.map((name:string)=>({name})),limit:String(action.limit)})});return result("Google Analytics 4",`ga4:${propertyId}:${action.metricId}`);}catch(error){return failure(error,"Google Analytics 4");}}
}

export class ShopifyDevelopmentStoreProvider extends ReadProviderBase implements CommerceProvider{
  readonly providerId="commerce" as const;readonly capabilities=new Set<BusinessActionRequest["capability"]>(["commerce.list_products","commerce.read_product","commerce.read_inventory","commerce.search_customers","commerce.list_orders","commerce.read_order","commerce.read_fulfillment","commerce.read_returns"]);constructor(readonly fetcher:Fetcher=fetch){super();}
  async execute(action:BusinessActionRequest,context?:BusinessProviderExecutionContext){if(!this.capabilities.has(action.capability))return failure(new ProviderHttpError("PERMISSION_DENIED",false),"Shopify development store");try{const credential=context?.credential;if(!credential?.shopDomain||!credential.apiVersion)throw new ProviderHttpError("EXPIRED_CREDENTIAL",false);const id="externalResourceId" in action?action.externalResourceId:null,root=action.capability.includes("product")||action.capability==="commerce.read_inventory"?"product":action.capability.includes("customer")?"customer":"order",query=id?`query AlexaNode($id: ID!) { node(id: $id) { id __typename } }`:`query AlexaList($first: Int!) { ${root}s(first: $first) { nodes { id } } }`,variables=id?{id}:{first:"limit" in action?action.limit:25};await bearer(this.fetcher,`https://${credential.shopDomain}/admin/api/${credential.apiVersion}/graphql.json`,token(context),{method:"POST",body:JSON.stringify({query,variables})},{"x-shopify-access-token":token(context)});return result("Shopify development store",id?`shopify:${id}`:null);}catch(error){return failure(error,"Shopify development store");}}
}
