import { describe,expect,it,vi } from "vitest";
import { BusinessActionRequestSchema } from "@alexa-control/shared";
import { GoogleAdsTestProvider,GoogleAnalytics4Provider,ShopifyDevelopmentStoreProvider,XeroSandboxAccountingProvider } from "./commercial-read-providers.js";

const ok=()=>Promise.resolve(new Response(JSON.stringify({validated:true}),{status:200,headers:{"content-type":"application/json"}}));
const base={companyId:crypto.randomUUID(),credentialBindingId:crypto.randomUUID()};
describe("credential-gated representative commercial read adapters",()=>{
  it("queries Xero through its reviewed tenant boundary",async()=>{const fetcher=vi.fn<typeof fetch>().mockImplementation(ok),provider=new XeroSandboxAccountingProvider(fetcher),credential={accessToken:"xero-access-token-fixture-long",tenantId:crypto.randomUUID()};const result=await provider.execute(BusinessActionRequestSchema.parse({capability:"accounting.read_pnl",idempotencyKey:"xero-pnl-1",reason:"Read sandbox P&L.",references:{},periodStart:"2026-09-01T00:00:00.000Z",periodEnd:"2026-09-04T00:00:00.000Z"}),{...base,credential});expect(result.outcome).toBe("VERIFIED");const [url,init]=fetcher.mock.calls[0]!,urlText=typeof url==="string"?url:url instanceof URL?url.href:url.url;expect(urlText).toContain("/Reports/ProfitAndLoss");expect(new Headers(init?.headers).get("xero-tenant-id")).toBe(credential.tenantId);expect(JSON.stringify(result)).not.toContain(credential.accessToken);});
  it("queries a Google Ads test account with a fixed bounded query",async()=>{const fetcher=vi.fn<typeof fetch>().mockImplementation(ok),provider=new GoogleAdsTestProvider(fetcher),credential={accessToken:"google-ads-access-token-long",developerToken:"developer-token-fixture",customerId:"1234567890"};const result=await provider.execute(BusinessActionRequestSchema.parse({capability:"ads.read_performance",idempotencyKey:"google-ads-read-1",reason:"Read test campaign performance.",references:{},externalResourceId:null,periodStart:"2026-09-01T00:00:00.000Z",periodEnd:"2026-09-04T00:00:00.000Z"}),{...base,credential});expect(result.outcome).toBe("VERIFIED");expect(fetcher).toHaveBeenCalledWith(expect.stringContaining("customers/1234567890/googleAds:searchStream"),expect.objectContaining({method:"POST"}));});
  it("queries GA4 with explicit period, metric, dimensions, and property",async()=>{const fetcher=vi.fn<typeof fetch>().mockImplementation(ok),provider=new GoogleAnalytics4Provider(fetcher),credential={accessToken:"google-analytics-access-token",propertyId:"123456789"};const result=await provider.execute(BusinessActionRequestSchema.parse({capability:"analytics.query_metric",idempotencyKey:"ga4-metric-read-1",reason:"Read a canonical analytics metric.",references:{},metricId:"conversions",dimensions:["sessionDefaultChannelGroup"],periodStart:"2026-09-01T00:00:00.000Z",periodEnd:"2026-09-04T00:00:00.000Z"}),{...base,credential});expect(result).toMatchObject({outcome:"VERIFIED",externalReferenceId:"ga4:123456789:conversions"});});
  it("restricts Shopify requests to a validated development-store host",async()=>{const fetcher=vi.fn<typeof fetch>().mockImplementation(ok),provider=new ShopifyDevelopmentStoreProvider(fetcher),credential={accessToken:"shopify-development-token-long",shopDomain:"alexa-fixture.myshopify.com",apiVersion:"2026-07"};const result=await provider.execute(BusinessActionRequestSchema.parse({capability:"commerce.list_products",idempotencyKey:"shopify-products-1",reason:"Read development-store products.",references:{},limit:10}),{...base,credential});expect(result.outcome).toBe("VERIFIED");expect(fetcher).toHaveBeenCalledWith("https://alexa-fixture.myshopify.com/admin/api/2026-07/graphql.json",expect.objectContaining({method:"POST"}));expect(JSON.stringify(result)).not.toContain(credential.accessToken);});
});
