import { CommercialFactSchema } from "@alexa-control/shared";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { companyScope } from "../companies/scope.js";
import { createIsolatedTestDatabase,safeTestDatabaseUrl } from "../persistence/test-database.js";
import type { PostgresDatabase } from "../persistence/database.js";
import { PostgresIntegrationStore } from "./postgres-store.js";

const connectionString=safeTestDatabaseUrl();
describe.skipIf(!connectionString)("Phase 26.2 PostgreSQL commercial fact isolation",()=>{
  let database:PostgresDatabase,cleanup:()=>Promise<void>,store:PostgresIntegrationStore;const ownerId=crypto.randomUUID(),companyA=crypto.randomUUID(),companyB=crypto.randomUUID(),at="2026-09-04T00:00:00.000Z";
  beforeAll(async()=>{const isolated=await createIsolatedTestDatabase(connectionString!,"phase262");database=isolated.database;cleanup=isolated.cleanup;await database.pool.query("INSERT INTO owners(id,email,password_hash,record,created_at,updated_at) VALUES($1,$2,'test-only',$3,$4,$4)",[ownerId,`phase262-${ownerId}@example.test`,{id:ownerId},at]);for(const [id,slug] of [[companyA,"alpha"],[companyB,"beta"]])await database.pool.query("INSERT INTO companies(id,owner_id,slug,name,status,timezone,default_currency,record,created_at,updated_at) VALUES($1,$2,$3,$3,'ACTIVE','UTC','USD',$4,$5,$5)",[id,ownerId,slug,{id,ownerId},at]);store=new PostgresIntegrationStore(database.pool);},60_000);
  afterAll(async()=>cleanup?.());
  it("persists one canonical source-role fact and filters sibling companies before return",async()=>{const fact=CommercialFactSchema.parse({id:crypto.randomUUID(),ownerId,companyId:companyA,canonicalEventId:"order-1",provider:"accounting",sourceRole:"BOOK_REVENUE",factType:"RAW_PROVIDER_FACT",eventType:"INVOICE_CREATED",externalEventId:"invoice-1",entityRef:"invoice-1",amountMinor:10_000,currency:"USD",occurredAt:at,providerTimezone:"America/New_York",createdAt:at});expect(await companyScope.run({ownerId,companyId:companyA,role:"OWNER",requestId:"test"},()=>store.saveCommercialFact(fact))).toBe(true);expect(await companyScope.run({ownerId,companyId:companyA,role:"OWNER",requestId:"test"},()=>store.saveCommercialFact({...fact,id:crypto.randomUUID(),externalEventId:"duplicate"}))).toBe(false);expect(await companyScope.run({ownerId,companyId:companyA,role:"OWNER",requestId:"test"},()=>store.listCommercialFacts(ownerId,10))).toEqual([fact]);expect(await companyScope.run({ownerId,companyId:companyB,role:"OWNER",requestId:"test"},()=>store.listCommercialFacts(ownerId,10))).toEqual([]);});

  it("atomically claims one cross-instance resource lease and recovers it with a higher fence",async()=>{const input={ownerId,companyId:companyA,provider:"ads",resourceType:"budget",resourceId:"campaign-1",now:at,expiresAt:"2026-09-04T00:00:30.000Z"};const [left,right]=await Promise.all([store.acquireCommercialMutationLease({...input,token:crypto.randomUUID()}),store.acquireCommercialMutationLease({...input,token:crypto.randomUUID()})]);expect([left,right].filter(Boolean)).toHaveLength(1);const winner=(left??right)!;const recovered=await store.acquireCommercialMutationLease({...input,token:crypto.randomUUID(),now:"2026-09-04T00:00:31.000Z",expiresAt:"2026-09-04T00:01:01.000Z"});expect(recovered?.fence).toBe(winner.fence+1);expect(await store.validateCommercialMutationLease({...input,token:winner.token,fence:winner.fence,now:"2026-09-04T00:00:31.000Z"})).toBe(false);expect(await store.validateCommercialMutationLease({...input,token:recovered!.token,fence:recovered!.fence,now:"2026-09-04T00:00:31.000Z"})).toBe(true);expect(await store.releaseCommercialMutationLease({...input,token:winner.token,fence:winner.fence})).toBe(false);});

  it("serializes concurrent aggregate reservations without exceeding a per-currency daily ceiling",async()=>{const make=(amountMinor:number,currency="SGD")=>({id:crypto.randomUUID(),ownerId,companyId:companyA,provider:"payments",actionClass:"REFUND" as const,currency,dayKey:"2026-09-04",amountMinor,idempotencyKey:crypto.randomUUID(),status:"RESERVED" as const,createdAt:at,updatedAt:at});expect((await store.reserveCommercialAggregate({reservation:make(9_000),limitMinor:10_000})).accepted).toBe(true);const [left,right]=await Promise.all([store.reserveCommercialAggregate({reservation:make(1_000),limitMinor:10_000}),store.reserveCommercialAggregate({reservation:make(1_000),limitMinor:10_000})]);expect([left.accepted,right.accepted].filter(Boolean)).toHaveLength(1);expect((await store.reserveCommercialAggregate({reservation:make(10_000,"USD"),limitMinor:10_000})).accepted).toBe(true);});

  it("uses compare-and-swap workflow transitions to reject duplicate workers",async()=>{const record={id:crypto.randomUUID(),ownerId,companyId:companyA,template:"REFUND" as const,triggerKey:"refund-pg-1",status:"PLANNED" as const,step:0,state:{templateVersion:1},createdAt:at,updatedAt:at};await store.saveCommercialWorkflow(record);const advanced={...record,step:1,updatedAt:"2026-09-04T00:00:01.000Z"};const claims=await Promise.all([store.transitionCommercialWorkflow(advanced,0,"PLANNED"),store.transitionCommercialWorkflow(advanced,0,"PLANNED")]);expect(claims.filter(Boolean)).toHaveLength(1);expect(await store.findCommercialWorkflow(ownerId,companyA,"REFUND","refund-pg-1")).toMatchObject({step:1});expect(await store.findCommercialWorkflow(ownerId,companyB,"REFUND","refund-pg-1")).toBeUndefined();});
});
