import { describe,expect,it,vi } from "vitest";
import { BusinessActionRequestSchema } from "@alexa-control/shared";
import { StripeTestPaymentsProvider } from "./stripe-provider.js";

const context={companyId:crypto.randomUUID(),credentialBindingId:crypto.randomUUID(),credential:{apiKey:"sk_test_reviewed_fixture_123456789"},mutationFence:7};
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json"}});

describe("reviewed Stripe test-mode provider",()=>{
  it("reads Stripe test state without exposing the secret",async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(json({id:"pi_test_1",object:"payment_intent",status:"succeeded"}));const provider=new StripeTestPaymentsProvider(fetcher);const result=await provider.execute(BusinessActionRequestSchema.parse({capability:"payments.read",idempotencyKey:"stripe-read-1",reason:"Read a test payment.",references:{},externalResourceId:"pi_test_1"}),context);expect(result).toMatchObject({outcome:"VERIFIED",externalReferenceId:"stripe:payment_intent:pi_test_1"});const [url,init]=fetcher.mock.calls[0]!,urlText=typeof url==="string"?url:url instanceof URL?url.href:url.url;expect(urlText).toBe("https://api.stripe.com/v1/payment_intents/pi_test_1");expect(new Headers(init?.headers).get("authorization")).toMatch(/^Bearer sk_test_/);expect(JSON.stringify(result)).not.toContain(context.credential.apiKey);});
  it("uses Stripe idempotency and fencing for an approved test refund",async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(json({id:"re_test_1",object:"refund",status:"succeeded"}));const provider=new StripeTestPaymentsProvider(fetcher),action=BusinessActionRequestSchema.parse({capability:"payments.execute_refund",idempotencyKey:"stripe-refund-1",reason:"Execute an approved sandbox refund.",references:{},externalResourceId:"pi_test_1",amountMinor:500,currency:"USD",expectedVersion:"succeeded"});const first=await provider.execute(action,context),duplicate=await provider.execute(action,context);expect(first).toEqual(duplicate);expect(fetcher).toHaveBeenCalledTimes(1);const init=fetcher.mock.calls[0]![1]!;expect(new Headers(init.headers).get("idempotency-key")).toBe("stripe-refund-1");expect(init.body instanceof URLSearchParams?init.body.toString():"").toContain("metadata%5Balexa_fence%5D=7");});
  it("never accepts a production Stripe key",async()=>{const provider=new StripeTestPaymentsProvider(vi.fn<typeof fetch>());expect(await provider.health({...context,credential:{apiKey:"sk_live_forbidden_123456789"}})).toMatchObject({state:"REAUTH_REQUIRED"});const result=await provider.execute(BusinessActionRequestSchema.parse({capability:"payments.read",idempotencyKey:"stripe-live-deny",reason:"Must deny a production key.",references:{},externalResourceId:"pi_1"}),{...context,credential:{apiKey:"sk_live_forbidden_123456789"}});expect(result).toMatchObject({outcome:"FAILED",failureKind:"EXPIRED_CREDENTIAL"});});
});
