import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, BarChart3, BrainCircuit, CalendarClock, Goal, ListChecks, ShieldAlert } from "lucide-react";
import type { ApiClient } from "./api.js";

export const ExecutivePage = ({ apiClient }: { apiClient: ApiClient }) => {
  const result = useQuery({ queryKey: ["executive-dashboard"], queryFn: apiClient.getExecutiveDashboard, refetchInterval: 30_000 });
  const queryClient = useQueryClient();
  const data = result.data;
  const reflection=useQuery({queryKey:["reflection-dashboard"],queryFn:apiClient.getReflectionDashboard,refetchInterval:30_000}).data;
  const skills=useQuery({queryKey:["skill-evolution-dashboard"],queryFn:apiClient.getSkillEvolutionDashboard,refetchInterval:30_000}).data;
  const refreshSkills=()=>queryClient.invalidateQueries({queryKey:["skill-evolution-dashboard"]});
  const mutate=useMutation({mutationFn:(fn:()=>Promise<unknown>)=>fn(),onSuccess:refreshSkills});
  return <section className="placeholder-page wide-page governance-page">
    <p className="eyebrow">Phase 21B</p><h1>Executive</h1>
    <p>Grounded priorities, plans, decisions, KPIs, and risks. Recommendations remain advisory and cannot approve or execute work.</p>
    <section className="status-grid">
      <article className="status-card"><span><BrainCircuit size={14}/> Health</span><strong>{data?.health ?? "UNKNOWN"}</strong><small>Deterministic assessment</small></article>
      <article className="status-card"><span><Goal size={14}/> Active goals</span><strong>{data?.goals.filter((item) => item.status === "ACTIVE").length ?? 0}</strong><small>{data?.objectives.length ?? 0} objectives</small></article>
      <article className="status-card"><span><ShieldAlert size={14}/> Open risks</span><strong>{data?.risks.filter((item) => ["OPEN","MATERIALIZED"].includes(item.status)).length ?? 0}</strong><small>{data?.alerts.filter((item) => !item.resolvedAt).length ?? 0} active alerts</small></article>
      <article className="status-card"><span><ListChecks size={14}/> Decisions</span><strong>{data?.decisions.filter((item) => item.status === "PROPOSED").length ?? 0}</strong><small>Separate from approvals</small></article>
    </section>
    <section className="dashboard-grid two-column-grid">
      <article className="panel"><h2>Priority stack</h2>{data?.priorities.length ? <ol>{data.priorities.map((item) => <li key={item.taskId ?? item.title}><strong>{item.title}</strong><span>{item.tier} · {item.score}</span><small>{item.reasons.join(" · ")}</small></li>)}</ol> : <p>No grounded priorities available.</p>}</article>
      <article className="panel"><h2>Blockers</h2>{data?.blockers.length ? data.blockers.map((item) => <p className="warning-text" key={item}><AlertTriangle size={14}/> {item}</p>) : <p>No unresolved blockers.</p>}</article>
      <article className="panel"><h2>Goals & objectives</h2>{data?.goals.map((goal) => <div key={goal.id}><strong>{goal.title}</strong><p>{goal.status} · {goal.priority}</p><small>{data.objectives.filter((item) => item.goalId === goal.id).length} objectives · {goal.successCriteria.length} success criteria</small></div>)}</article>
      <article className="panel"><h2><CalendarClock size={16}/> Plans</h2>{data?.plans.map((plan) => <div key={plan.id}><strong>Plan v{plan.version} · {plan.feasibility}</strong><p>{plan.milestones.join(" · ") || "No milestones"}</p><small>{plan.effortMinutes} min · {plan.scheduleSuggestions.length} scheduled blocks · confidence {Math.round(plan.confidence * 100)}%</small></div>)}</article>
      <article className="panel"><h2><BarChart3 size={16}/> KPIs</h2>{data?.kpis.map((kpi) => <p key={kpi.id}><strong>{kpi.name}</strong> {kpi.currentValue}{kpi.unit} / {kpi.target}{kpi.unit}<small> {kpi.source} · {Math.round(kpi.confidence * 100)}%</small></p>)}</article>
      <article className="panel"><h2>Risks & alerts</h2>{data?.risks.map((risk) => <p key={risk.id}><strong>{risk.status}</strong> {risk.description}<small> severity {Math.round(risk.severity * 100)}%</small></p>)}</article>
      <article className="panel"><h2>Decision queue</h2>{data?.decisions.map((decision) => <div key={decision.id}><strong>{decision.question}</strong><p>{decision.recommendation} · {decision.status}</p><small>{decision.reversible} · confidence {Math.round(decision.confidence * 100)}%</small></div>)}</article>
      <article className="panel"><h2>Executive history</h2>{data?.history.slice(0,20).map((item) => <p key={item.id}><strong>{item.type}</strong> {item.summary}</p>)}</article>
      <article className="panel"><h2>Reflections</h2><p>{reflection?.summary.evaluated ?? 0} evaluated · {reflection?.summary.met ?? 0} met · {reflection?.summary.partial ?? 0} partial · {reflection?.summary.missed ?? 0} missed</p>{reflection?.reflections.slice(0,10).map(item=><div key={item.id}><strong>{item.reflectionType} · {item.outcome}</strong><p>{item.metrics.map(metric=>`${metric.name}: ${metric.actual ?? "unknown"}${metric.unit}`).join(" · ")}</p><small>Baseline {item.baselineVersion ?? "n/a"} · evidence {item.evidence.length} · confidence {Math.round(item.confidence*100)}%</small></div>)}</article>
      <article className="panel"><h2>Calibration & patterns</h2>{reflection?.calibrations.map(item=><p key={item.id}><strong>{item.category}</strong> {item.status} · {item.sampleCount}/{item.minimumSampleCount} samples · mean {Math.round(item.meanEstimate*100)/100} vs {Math.round(item.meanActual*100)/100} · bias {Math.round(item.biasPercent*100)/100}% · MAE {Math.round(item.meanAbsoluteError*100)/100} · {item.trend} · {item.fallbackLevel}<small> Scope {Object.entries(item.scope).filter(([,value])=>value).map(([key,value])=>`${key}=${value}`).join(", ") || "global"} · confidence {Math.round(item.confidence*100)}%</small></p>)}{reflection?.patterns.map(item=><p key={item.id}><strong>{item.status}</strong> {item.description}<small> {item.evidenceCount} supporting · {item.contradictionCount} contradicting</small></p>)}</article>
      <article className="panel"><h2>Routing economics</h2>{reflection?.routingEconomics.map(item=><p key={item.route}><strong>{item.route}</strong> {item.sampleCount} samples · success {item.successRate===null?"n/a":`${Math.round(item.successRate*100)}%`} · clarification {item.clarificationRate===null?"n/a":`${Math.round(item.clarificationRate*100)}%`} · latency {item.meanLatencyMs===null?"n/a":`${Math.round(item.meanLatencyMs)}ms`} · cost ${item.totalCostUsd.toFixed(4)} · cost/success {item.costPerSuccessfulOutcome===null?"n/a":item.costPerSuccessfulOutcome.toFixed(4)}</p>)}</article>
      <article className="panel"><h2>Skill Evolution</h2><p>{skills?.summary.activeSkills ?? 0} active · {skills?.summary.candidates ?? 0} candidates · {skills?.summary.testing ?? 0} testing · {skills?.summary.degraded ?? 0} degraded</p><button type="button" onClick={()=>mutate.mutate(()=>apiClient.runSkillDraftBenchmark())}>Run draft benchmark</button>{skills?.skills.slice(0,8).map(item=>{const active=skills.versions.find(version=>version.id===item.activeVersionId); const latest=skills.versions.find(version=>version.skillId===item.id); return <div key={item.id}><strong>{item.name}</strong><p>{item.status} · {item.healthState} · {item.riskClass} · v{active?.version ?? "draft"}</p><small>{item.usageCount} runs · success {item.successRate===null?"n/a":`${Math.round(item.successRate*100)}%`} · capabilities {item.requiredCapabilities.join(", ")}</small><p><button type="button" onClick={()=>mutate.mutate(()=>apiClient.validateSkillVersion(item.id,latest?.id))}>Validate</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.benchmarkSkillVersion(item.id,latest?.id))}>Sandbox</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.promoteSkillVersion(item.id,latest?.id))}>Promote</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.shadowSkillVersion(item.id,latest?.id))}>Shadow</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.canarySkillVersion(item.id,latest?.id))}>Canary</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.rollbackSkillVersion(item.id))}>Rollback</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.deprecateSkill(item.id))}>Deprecate</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.disableSkill(item.id))}>Disable</button></p></div>})}{skills?.candidates.slice(0,8).map(item=><div key={item.id}><strong>{item.title}</strong><p>{item.category} · {item.status} · evidence {item.supportingEvidence.length} · {item.riskClass}</p><small>{item.expectedBenefit} · capabilities {item.proposedCapabilities.join(", ") || "none"}</small><p><button type="button" onClick={()=>mutate.mutate(()=>apiClient.buildSkillCandidate(item.id))}>Build</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.dismissSkillCandidate(item.id))}>Dismiss</button> <button type="button" onClick={()=>mutate.mutate(()=>apiClient.suppressSkillCandidate(item.id))}>Don't suggest</button></p></div>)}<small>Unsafe accepted {skills?.summary.unsafeCapabilityAccepted ?? 0} · self approval {skills?.summary.selfApproval ?? 0} · policy mutation {skills?.summary.policyMutation ?? 0}</small></article>
      <article className="panel"><h2>Skill Benchmarks & History</h2>{skills?.benchmarks.slice(0,10).map(item=><p key={item.id}><strong>{item.profile}</strong> {item.successes}/{item.testCases} · {item.promotionRecommendation}<small> p95 {Math.round(item.latencyMsP95)}ms · cost ${item.costUsd.toFixed(4)} · regressions {item.regressions}</small></p>)}{skills?.evaluations.slice(0,8).map(item=><p key={item.id}><strong>{item.mode}</strong> {item.status} · samples {item.sampleCount}/{item.minimumSampleCount}<small>{item.reason} · rollback {item.rollbackRecommended ? "recommended" : "no"}</small></p>)}{skills?.draftBenchmarkRuns.slice(0,4).map(item=><p key={item.id}><strong>{item.baselineName ?? item.suiteVersion}</strong> {item.cases} cases · first pass {Math.round(item.structuredFirstPassRate*100)}% · deterministic repair {Math.round(item.afterDeterministicRepairRate*100)}% · model repair {Math.round(item.afterModelRepairRate*100)}%<small> unsafe accepted {item.unsafeProposalAccepted} · common failure {item.mostCommonFailureCategory ?? "none"} · p95 {Math.round(item.p95LatencyMs)}ms</small></p>)}{skills?.events.slice(0,12).map(item=><p key={item.id}><strong>{item.type}</strong> {item.summary}</p>)}</article>
    </section>
  </section>;
};
