import {
  BackgroundMonitorRecordSchema,
  ChecklistItemRecordSchema,
  ChecklistRecordSchema,
  CreateChecklistRequestSchema,
  CreateGoalRequestSchema,
  CreateRoutineRequestSchema,
  CreateTaskRequestSchema,
  GoalRecordSchema,
  RoutineRecordSchema,
  TaskCenterResponseSchema,
  TaskConditionSchema,
  TaskMetricRecordSchema,
  TaskNotificationSchema,
  TaskRecordSchema,
  TaskRunSchema,
  TaskSuggestionRecordSchema,
  TaskTriggerRequestSchema,
  TaskTriggerSchema,
  type CommandSafetyLevel,
  type IntentCategory,
  type MemoryEvidence,
  type TaskRecord,
} from "@alexa-control/shared";

import type { AgentSocietyService } from "../agent-society/service.js";
import type { GovernanceAuditWriter } from "../governance/approval-service.js";
import type { IntentExecutionService } from "../intent/service.js";
import type { TaskStore } from "./store.js";

const evidenceFor = (at: string, reference: string): MemoryEvidence[] => [
  {
    sourceType: "manual",
    reference,
    excerpt:
      "Generated by the Autonomous Task Engine. Proactive coordination remains governed and approval-gated.",
    observedAt: at,
  },
];

const includesAny = (value: string, words: string[]) =>
  words.some((word) => value.includes(word));

export class TaskEngineService {
  private lifecycleSink:
    | {
        ensurePeriodicSchedules(ownerId: string): Promise<void>;
        handleTaskTrigger(input: {
          ownerId: string;
          task: TaskRecord;
          reason: string;
          signal?: AbortSignal;
        }): Promise<unknown>;
        handleEvent(input: {
          ownerId: string;
          eventType: string;
          scopeId: string;
          baselineVersion: string;
          sourceSnapshot: unknown;
          signal?: AbortSignal;
        }): Promise<unknown>;
      }
    | undefined;
  constructor(
    readonly store: TaskStore,
    readonly intent: IntentExecutionService,
    readonly society: AgentSocietyService,
    readonly audit: GovernanceAuditWriter,
    readonly now: () => Date = () => new Date(),
  ) {}

  setLifecycleSink(sink: NonNullable<TaskEngineService["lifecycleSink"]>) {
    this.lifecycleSink = sink;
  }

  async emitLifecycleEvent(input: {
    ownerId: string;
    eventType: string;
    scopeId: string;
    baselineVersion: string;
    sourceSnapshot: unknown;
    signal?: AbortSignal;
  }) {
    if (!this.lifecycleSink) return null;
    return this.lifecycleSink.handleEvent(input);
  }

  async dashboard(ownerId: string) {
    await this.ensureBaseline(ownerId);
    await this.lifecycleSink?.ensurePeriodicSchedules(ownerId);
    return TaskCenterResponseSchema.parse({
      tasks: await this.store.listTasks(ownerId, 500),
      runs: await this.store.listRuns(ownerId, 500),
      triggers: await this.store.listTriggers(ownerId, 500),
      conditions: await this.store.listConditions(ownerId, 500),
      dependencies: await this.store.listDependencies(ownerId, 500),
      notifications: await this.store.listNotifications(ownerId, 500),
      goals: await this.store.listGoals(ownerId, 500),
      checklists: await this.store.listChecklists(ownerId, 500),
      checklistItems: await this.store.listChecklistItems(ownerId, 1_000),
      routines: await this.store.listRoutines(ownerId, 500),
      monitors: await this.store.listMonitors(ownerId, 500),
      metrics: await this.store.listMetrics(ownerId, 500),
      suggestions: await this.store.listSuggestions(ownerId, 500),
      proactive: true,
      autonomousExecutionBypassesGovernance: false,
    });
  }

  async createTask(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    await this.ensureBaseline(input.ownerId, input.requestId);
    const parsed = CreateTaskRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const taskId = crypto.randomUUID();
    const safetyLevel = this.safetyFor(parsed.goal, parsed.category);
    const requiresApproval = ["moderate_risk", "high_risk", "critical"].includes(
      safetyLevel,
    );
    const task = TaskRecordSchema.parse({
      id: taskId,
      ownerId: input.ownerId,
      name: parsed.name,
      description: parsed.description,
      goal: parsed.goal,
      priority: parsed.priority,
      category: parsed.category,
      type: parsed.type,
      status: requiresApproval ? "waiting_approval" : "scheduled",
      schedule: this.scheduleFor(parsed, at),
      triggerSummary: `${parsed.triggerType} trigger registered.`,
      conditionSummary: parsed.condition || "No additional condition.",
      dependencyIds: [],
      executionPolicy: {
        safetyLevel,
        requiresApproval,
        requiresRecentAuthentication:
          safetyLevel === "high_risk" || safetyLevel === "critical",
        requiresPrivateNetwork: safetyLevel !== "informational",
        requiresTrustedDevice: safetyLevel !== "informational",
        allowedProviders: this.providersFor(parsed.category),
        autonomousExecutionAllowed: false,
      },
      approvalPolicy: requiresApproval
        ? safetyLevel === "high_risk" || safetyLevel === "critical"
          ? "recent_authentication"
          : "explicit"
        : "none",
      assignedAgentIds: this.agentsFor(parsed.goal, parsed.category),
      retryPolicy: {
        maxRetries: safetyLevel === "informational" ? 1 : 0,
        strategy: safetyLevel === "informational" ? "linear" : "none",
      },
      timeoutSeconds: 1_800,
      deadlineAt: parsed.deadlineAt,
      successCriteria: [
        "Task state is persisted.",
        "Any future execution routes through existing governed systems.",
      ],
      failureCriteria: [
        "Required approval is unavailable.",
        "Safety state is unknown.",
      ],
      rollbackStrategy:
        "No autonomous mutation occurs. Future provider work must use provider-specific rollback.",
      metadata: { source: "task_engine" },
      version: "1.0.0",
      createdAt: at,
      updatedAt: at,
    });
    const trigger = TaskTriggerSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      taskId,
      type: parsed.triggerType,
      source: "task_engine",
      eventName:
        parsed.triggerType === "manual" ? "manual_trigger" : parsed.triggerType,
      enabled: true,
      metadata: {},
      createdAt: at,
      updatedAt: at,
    });
    const condition = TaskConditionSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      taskId,
      logic: "AND",
      field: "owner_context",
      operator: parsed.condition ? "contains" : "exists",
      expected: parsed.condition || "ready",
      windowSeconds: null,
      enabled: Boolean(parsed.condition),
      createdAt: at,
      updatedAt: at,
    });
    const notification = TaskNotificationSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      taskId,
      channel: "desktop",
      title: task.name,
      message: `Task scheduled: ${task.goal}`,
      status: "pending",
      escalationLevel: task.priority === "urgent" ? 2 : 0,
      scheduledFor: task.schedule.preview[0] ?? task.schedule.startAt,
      sentAt: null,
      createdAt: at,
      updatedAt: at,
    });
    await this.store.saveTask(task);
    await this.store.saveTrigger(trigger);
    await this.store.saveCondition(condition);
    await this.store.saveNotification(notification);
    if (
      ["software_development", "planning", "repository_operations"].includes(
        task.category,
      )
    ) {
      await this.society.formTeam({
        ownerId: input.ownerId,
        requestId: input.requestId,
        ipAddress: input.ipAddress,
        body: { goal: task.goal, repositoryIds: [] },
      });
    }
    await this.audit({
      eventType: "TASK_CREATED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Autonomous task created without bypassing governance.",
      metadata: {
        taskId: task.id,
        safetyLevel,
        requiresApproval,
        autonomousExecutionAllowed: false,
      },
      requestId: input.requestId,
    });
    await this.audit({
      eventType: requiresApproval ? "TASK_APPROVAL_REQUIRED" : "TASK_SCHEDULED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: requiresApproval
        ? "Task requires approval before execution."
        : "Task scheduled for governed processing.",
      metadata: { taskId: task.id },
      requestId: input.requestId,
    });
    return TaskCenterResponseSchema.parse(await this.dashboard(input.ownerId));
  }

  async triggerTask(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    const parsed = TaskTriggerRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const task = await this.store.getTask(input.ownerId, parsed.taskId);
    if (!task) throw new Error("Task not found.");
    const reflectionTask = task.metadata.systemTask === "reflection_review";
    const command =
      reflectionTask || task.executionPolicy.requiresApproval || task.status === "waiting_approval"
        ? null
        : await this.intent.submit({
            ownerId: input.ownerId,
            requestId: input.requestId,
            ipAddress: input.ipAddress,
            body: {
              request: task.goal,
              source: "scheduled_task",
            },
          });
    if (reflectionTask) {
      await this.lifecycleSink?.handleTaskTrigger({
        ownerId: input.ownerId,
        task,
        reason: parsed.reason,
      });
    }
    const run = TaskRunSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      taskId: task.id,
      status: task.executionPolicy.requiresApproval ? "waiting_approval" : reflectionTask ? "completed" : "queued",
      startedAt: reflectionTask ? at : null,
      completedAt: reflectionTask ? at : null,
      commandId: command?.command.id ?? null,
      outcome: task.executionPolicy.requiresApproval
        ? "Approval required before routing."
        : reflectionTask
          ? "Bounded reflection review completed through the Reflection Engine."
        : `Queued governed command from task trigger: ${parsed.reason}`,
      retryCount: 0,
      createdAt: at,
      updatedAt: at,
    });
    await this.store.saveRun(run);
    await this.audit({
      eventType: "TASK_RUN_QUEUED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Task trigger evaluated and run record created.",
      metadata: {
        taskId: task.id,
        runId: run.id,
        commandId: run.commandId,
        autonomousExecutionAllowed: false,
      },
      requestId: input.requestId,
    });
    return TaskCenterResponseSchema.parse(await this.dashboard(input.ownerId));
  }

  async createGoal(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    await this.ensureBaseline(input.ownerId, input.requestId);
    const parsed = CreateGoalRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const goal = GoalRecordSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      title: parsed.title,
      description: parsed.description,
      status: "active",
      priority: parsed.priority,
      completionPercent: 0,
      supportingTaskIds: [],
      createdAt: at,
      updatedAt: at,
    });
    await this.store.saveGoal(goal);
    await this.audit({
      eventType: "GOAL_TASK_CREATED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Long-term goal recorded for task planning.",
      metadata: { goalId: goal.id },
      requestId: input.requestId,
    });
    return TaskCenterResponseSchema.parse(await this.dashboard(input.ownerId));
  }

  async createRoutine(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    await this.ensureBaseline(input.ownerId, input.requestId);
    const parsed = CreateRoutineRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const routine = RoutineRecordSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      name: parsed.name,
      description: parsed.description,
      mode: parsed.mode,
      taskIds: parsed.taskIds,
      enabled: true,
      createdAt: at,
      updatedAt: at,
    });
    await this.store.saveRoutine(routine);
    await this.audit({
      eventType: "ROUTINE_CREATED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Reusable routine created.",
      metadata: { routineId: routine.id },
      requestId: input.requestId,
    });
    return TaskCenterResponseSchema.parse(await this.dashboard(input.ownerId));
  }

  async createChecklist(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    await this.ensureBaseline(input.ownerId, input.requestId);
    const parsed = CreateChecklistRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const checklist = ChecklistRecordSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      name: parsed.name,
      category: parsed.category,
      reusable: parsed.reusable,
      createdAt: at,
      updatedAt: at,
    });
    await this.store.saveChecklist(checklist);
    for (const [index, label] of parsed.items.entries()) {
      await this.store.saveChecklistItem(
        ChecklistItemRecordSchema.parse({
          id: crypto.randomUUID(),
          ownerId: input.ownerId,
          checklistId: checklist.id,
          label,
          status: "open",
          sequence: index + 1,
          createdAt: at,
          updatedAt: at,
        }),
      );
    }
    await this.audit({
      eventType: "CHECKLIST_CREATED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Checklist created.",
      metadata: { checklistId: checklist.id, itemCount: parsed.items.length },
      requestId: input.requestId,
    });
    return TaskCenterResponseSchema.parse(await this.dashboard(input.ownerId));
  }

  async ensureBaseline(ownerId: string, requestId = "system") {
    if ((await this.store.listMonitors(ownerId, 1)).length === 0) {
      const at = this.now().toISOString();
      const next = new Date(Date.parse(at) + 15 * 60_000).toISOString();
      await this.store.saveMonitor(
        BackgroundMonitorRecordSchema.parse({
          id: crypto.randomUUID(),
          ownerId,
          name: "Workflow queue monitor",
          target: "workflow_engine",
          monitorType: "workflow",
          status: "active",
          lastCheckedAt: null,
          nextCheckAt: next,
          lightweight: true,
          createdAt: at,
          updatedAt: at,
        }),
      );
      await this.store.saveMetric(
        TaskMetricRecordSchema.parse({
          id: crypto.randomUUID(),
          ownerId,
          metricName: "task_readiness",
          value: 0.82,
          trend: 0,
          summary:
            "Task engine can persist schedules, triggers, conditions, reminders, routines, and governed run records.",
          measuredAt: at,
        }),
      );
      await this.store.saveSuggestion(
        TaskSuggestionRecordSchema.parse({
          id: crypto.randomUUID(),
          ownerId,
          title: "Create a morning briefing routine",
          rationale:
            "A recurring briefing can summarize repositories, workflows, reminders, and security status without executing consequential actions.",
          suggestedTask:
            "Every weekday morning, summarize open workflows, active risks, and upcoming approvals.",
          confidence: 0.76,
          evidence: evidenceFor(at, "Task baseline suggestion"),
          createdAt: at,
        }),
      );
      await this.audit({
        eventType: "BACKGROUND_MONITOR_REGISTERED",
        ownerId,
        ipAddress: "system",
        outcome: "SUCCESS",
        reason: "Baseline lightweight monitor initialized.",
        metadata: { autonomousExecutionAllowed: false },
        requestId,
      });
    }
  }

  private scheduleFor(
    parsed: ReturnType<typeof CreateTaskRequestSchema.parse>,
    at: string,
  ) {
    const start = parsed.startAt ?? at;
    return {
      kind: parsed.scheduleKind,
      timezone: parsed.timezone,
      startAt: parsed.scheduleKind === "none" ? null : start,
      endAt: null,
      cronExpression: null,
      intervalSeconds: parsed.scheduleKind === "hourly" ? 3_600 : null,
      quietHours: [],
      blackoutPeriods: [],
      preview: this.previewFor(parsed.scheduleKind, start),
    };
  }

  private previewFor(kind: string, start: string) {
    if (kind === "none") return [];
    const startMs = Date.parse(start);
    const step =
      kind === "hourly"
        ? 3_600_000
        : kind === "weekly"
          ? 7 * 86_400_000
          : kind === "monthly"
            ? 30 * 86_400_000
            : 86_400_000;
    return Array.from({ length: kind === "once" ? 1 : 5 }, (_, index) =>
      new Date(startMs + index * step).toISOString(),
    );
  }

  private safetyFor(goal: string, category: IntentCategory): CommandSafetyLevel {
    const value = goal.toLowerCase();
    if (includesAny(value, ["delete", "bank", "payment", "sudo", "admin"])) {
      return "critical";
    }
    if (includesAny(value, ["deploy", "send", "email", "write", "push", "merge"])) {
      return "high_risk";
    }
    if (
      ["repository_operations", "software_development", "automation"].includes(category)
    ) {
      return "moderate_risk";
    }
    if (
      ["research", "knowledge_retrieval", "monitoring", "notifications"].includes(
        category,
      )
    ) {
      return "read_only";
    }
    return "low_risk";
  }

  private providersFor(
    category: IntentCategory,
  ): TaskRecord["executionPolicy"]["allowedProviders"] {
    if (category === "software_development")
      return ["workflow_engine", "agent_society"];
    if (category === "repository_operations") return ["read_only_execution"];
    if (category === "integrations" || category === "communication") {
      return ["integration_registry"];
    }
    if (category === "monitoring" || category === "notifications") {
      return ["intent_engine", "manual_owner"];
    }
    return ["agent_society", "manual_owner"];
  }

  private agentsFor(goal: string, category: IntentCategory) {
    const value = goal.toLowerCase();
    const agents = ["planning_agent"];
    if (category === "software_development") agents.push("coding_agent");
    if (includesAny(value, ["security", "auth", "risk"])) agents.push("security_agent");
    if (includesAny(value, ["test", "validation", "verify"]))
      agents.push("testing_agent");
    if (includesAny(value, ["doc", "summary", "briefing"])) {
      agents.push("documentation_agent");
    }
    return [...new Set(agents)];
  }
}
