import type { NetworkVerifier } from "@alexa-control/shared";

import type { IdentityService } from "../identity/service.js";
import type { SecurityMiddleware } from "../identity/security.js";
import type {
  GovernanceAuditWriter,
  ApprovalService,
} from "../governance/approval-service.js";
import type { GovernanceService } from "../governance/service.js";
import type { RegistryService } from "../governance/registry-service.js";
import type { GovernanceStore } from "../governance/store.js";
import type { Awaitable } from "../identity/store.js";
import type { SecurityStateService } from "../security-state/service.js";
import type { ExecutionService } from "../execution/service.js";
import type { ExecutionStore } from "../execution/store.js";
import type { ServerExecutionSigner } from "../execution/server-key-store.js";
import type { RepositoryService } from "../repositories/service.js";
import type { RepositoryStore } from "../repositories/store.js";
import type { PatchService } from "../patches/service.js";
import type { PatchStore } from "../patches/store.js";
import type { ValidationService } from "../validation/service.js";
import type { ValidationStore } from "../validation/store.js";
import type { WorkflowEngineService } from "../workflows/service.js";
import type { WorkflowStore } from "../workflows/store.js";
import type { IntegrationRegistryService } from "../integrations/service.js";
import type { IntegrationStore } from "../integrations/store.js";
import type { AgentRegistryService } from "../agents/service.js";
import type { AgentFactoryService } from "../agents/factory.js";
import type { AgentStore } from "../agents/store.js";
import type { AgentOsService } from "../agents/os-service.js";
import type { AgentOsStore } from "../agents/os-store.js";
import type { ExternalHarvestService } from "../external-harvest/service.js";
import type { AgentCognitionService } from "../agent-cognition/service.js";
import type { AgentCognitionStore } from "../agent-cognition/store.js";
import type { AgentEvolutionService } from "../agent-evolution/service.js";
import type { AgentEvolutionStore } from "../agent-evolution/store.js";
import type { AgentSocietyService } from "../agent-society/service.js";
import type { AgentSocietyStore } from "../agent-society/store.js";
import type { AgentEconomyService } from "../agent-economy/service.js";
import type { AgentEconomyStore } from "../agent-economy/store.js";
import type { AgentWorkforceService } from "../agent-workforce/service.js";
import type { AgentWorkforceStore } from "../agent-workforce/store.js";
import type { WorkforceRuntimeService } from "../workforce-runtime/service.js";
import type { WorkforceRuntimeStore } from "../workforce-runtime/store.js";
import type { MemoryIndexerService } from "../memory/service.js";
import type { ExplicitMemoryTeachingService } from "../memory/explicit-teaching-service.js";
import type { MemoryStore } from "../memory/store.js";
import type { CacheService } from "../intelligence/cache-service.js";
import type { EmbeddingService } from "../intelligence/embedding-service.js";
import type { InfrastructureMetricsService } from "../intelligence/infrastructure-service.js";
import type { RedisService } from "../intelligence/redis-service.js";
import type { RetrievalService } from "../intelligence/retrieval-service.js";
import type { WorkerService } from "../intelligence/worker-service.js";
import type { EngineeringAdvisorService } from "../advisor/service.js";
import type { AdvisorStore } from "../advisor/store.js";
import type { IntentExecutionService } from "../intent/service.js";
import type { IntentStore } from "../intent/store.js";
import type { TaskEngineService } from "../tasks/service.js";
import type { TaskStore } from "../tasks/store.js";
import type { DesktopCapabilityService } from "../desktop/service.js";
import type { DesktopStore } from "../desktop/store.js";
import type { ApplicationRegistryService } from "../application-adapters/service.js";
import type { ApplicationAdapterStore } from "../application-adapters/store.js";
import type { ApplicationDiscoveryService } from "../application-discovery/service.js";
import type { ApplicationDiscoveryStore } from "../application-discovery/store.js";
import type { AdapterRegistryService } from "../adapter-sdk/service.js";
import type { AdapterSdkStore } from "../adapter-sdk/store.js";
import type { CoreAdapterService } from "../core-adapters/service.js";
import type { CoreAdapterStore } from "../core-adapters/store.js";
import type { CrossApplicationWorkflowService } from "../cross-application-workflows/service.js";
import type { CrossApplicationWorkflowStore } from "../cross-application-workflows/store.js";
import type { ApplicationIntelligenceService } from "../application-intelligence/service.js";
import type { ApplicationIntelligenceStore } from "../application-intelligence/store.js";
import type { WorkspaceIntelligenceService } from "../workspace-intelligence/service.js";
import type { WorkspaceIntelligenceStore } from "../workspace-intelligence/store.js";
import type { SemanticIndexerService } from "../deep-indexers/service.js";
import type { DeepIndexerStore } from "../deep-indexers/store.js";
import type { DesktopSkillExecutionService } from "../desktop-skills/service.js";
import type { DesktopSkillStore } from "../desktop-skills/store.js";
import type { NativeProviderRuntime } from "../native-providers/service.js";
import type { NativeProviderStore } from "../native-providers/store.js";
import type { ApplicationInteractionService } from "../application-interactions/service.js";
import type { SpatialInteractionService } from "../spatial/service.js";
import type { SpatialStore } from "../spatial/store.js";
import type { VoiceRuntimeService } from "../voice/service.js";
import type { VoiceCaptureLeaseService } from "../voice/capture-lease.js";
import type { ActiveContextService } from "../active-context/service.js";
import type { VoiceStore } from "../voice/store.js";
import type { IntentRecordingService } from "../intent-recording/service.js";
import type { IntentRecordingStore } from "../intent-recording/store.js";
import type { SemanticRetrievalService } from "../semantic/service.js";
import type { SemanticRetrievalStore } from "../semantic/store.js";
import type { HumanUnderstandingService } from "../human-understanding/service.js";
import type { HumanUnderstandingStore } from "../human-understanding/store.js";
import type { PersonalKnowledgeGraphService } from "../knowledge-graph/service.js";
import type { KnowledgeGraphStore } from "../knowledge-graph/store.js";
import type { LearningEngineService } from "../learning-engine/service.js";
import type { LearningEngineStore } from "../learning-engine/store.js";
import type { CognitiveQueryService } from "../memory-studio/service.js";
import type { MemoryStudioStore } from "../memory-studio/store.js";
import type { LocalAIService } from "../local-ai/service.js";
import type { AIRuntimeService } from "../ai/runtime-service.js";
import type { AIRouterService } from "../ai/router/service.js";
import type { AIEconomicsService } from "../ai/economics/service.js";
import type { CognitiveContextService } from "../ai/context/service.js";
import type { AIBenchmarkRunner } from "../ai/benchmark/service.js";
import type { ExecutiveBrainService } from "../executive/service.js";
import type { ExecutiveStore } from "../executive/store.js";
import type { ObjectiveEngineService } from "../objectives/service.js";
import type { ExperimentService } from "../experiments/service.js";
import type { ReflectionEngineService } from "../reflection/service.js";
import type { ReflectionStore } from "../reflection/store.js";
import type { SkillEvolutionService } from "../skill-evolution/service.js";
import type { SkillEvolutionStore } from "../skill-evolution/store.js";
import type { CapabilityStudioService } from "../capability-studio/service.js";
import type { CapabilityStudioStore } from "../capability-studio/store.js";
import type { BusinessOSService } from "../business-os/service.js";

export interface ApiRouteContext {
  deploymentMode: "private" | "cloud";
  identity: IdentityService;
  security: SecurityMiddleware;
  securityState: SecurityStateService;
  networkVerifier: NetworkVerifier;
  cookieName: string;
  secureCookies: boolean;
  sessionTtlSeconds: number;
  signedRequestToleranceSeconds: number;
  privateNetworkRequired: boolean;
  governance: GovernanceService;
  governanceStore: GovernanceStore;
  registry: RegistryService;
  approvals: ApprovalService;
  governanceAudit: GovernanceAuditWriter;
  executionEnabled: () => false;
  emergencyStopActive: () => Awaitable<boolean>;
  activateEmergencyStop: () => Awaitable<void>;
  releaseEmergencyStop: () => Awaitable<void>;
  persistenceMode: "in_memory_development" | "postgresql";
  databaseReady: () => Promise<boolean>;
  migrationState: () => Promise<"current" | "outdated" | "unknown">;
  productionNetworkVerifierConfigured: boolean;
  trustedProxyConfigured: boolean;
  csrfProtection: true;
  executions: ExecutionService;
  executionStore: ExecutionStore;
  repositories: RepositoryService;
  repositoryStore: RepositoryStore;
  patches: PatchService;
  patchStore: PatchStore;
  validations: ValidationService;
  validationStore: ValidationStore;
  workflows: WorkflowEngineService;
  workflowStore: WorkflowStore;
  integrations: IntegrationRegistryService;
  integrationStore: IntegrationStore;
  agents: AgentRegistryService;
  agentFactory: AgentFactoryService;
  agentStore: AgentStore;
  agentOs: AgentOsService;
  agentOsStore: AgentOsStore;
  externalHarvest: ExternalHarvestService;
  agentCognition: AgentCognitionService;
  agentCognitionStore: AgentCognitionStore;
  agentEvolution: AgentEvolutionService;
  agentEvolutionStore: AgentEvolutionStore;
  agentSociety: AgentSocietyService;
  agentSocietyStore: AgentSocietyStore;
  agentEconomy: AgentEconomyService;
  agentEconomyStore: AgentEconomyStore;
  agentWorkforce: AgentWorkforceService;
  agentWorkforceStore: AgentWorkforceStore;
  workforceRuntime: WorkforceRuntimeService;
  workforceRuntimeStore: WorkforceRuntimeStore;
  memory: MemoryIndexerService;
  explicitMemoryTeaching: ExplicitMemoryTeachingService;
  memoryStore: MemoryStore;
  redis: RedisService;
  cache: CacheService;
  embeddings: EmbeddingService;
  retrieval: RetrievalService;
  workers: WorkerService;
  infrastructure: InfrastructureMetricsService;
  advisor: EngineeringAdvisorService;
  advisorStore: AdvisorStore;
  intentExecution: IntentExecutionService;
  intentStore: IntentStore;
  tasks: TaskEngineService;
  taskStore: TaskStore;
  desktop: DesktopCapabilityService;
  desktopStore: DesktopStore;
  applicationAdapters: ApplicationRegistryService;
  applicationAdapterStore: ApplicationAdapterStore;
  applicationDiscovery: ApplicationDiscoveryService;
  applicationDiscoveryStore: ApplicationDiscoveryStore;
  adapterSdk: AdapterRegistryService;
  adapterSdkStore: AdapterSdkStore;
  coreAdapters: CoreAdapterService;
  coreAdapterStore: CoreAdapterStore;
  crossApplicationWorkflows: CrossApplicationWorkflowService;
  crossApplicationWorkflowStore: CrossApplicationWorkflowStore;
  applicationIntelligence: ApplicationIntelligenceService;
  applicationIntelligenceStore: ApplicationIntelligenceStore;
  workspaceIntelligence: WorkspaceIntelligenceService;
  workspaceIntelligenceStore: WorkspaceIntelligenceStore;
  semanticIndexers: SemanticIndexerService;
  deepIndexerStore: DeepIndexerStore;
  desktopSkills: DesktopSkillExecutionService;
  desktopSkillStore: DesktopSkillStore;
  nativeProviders: NativeProviderRuntime;
  nativeProviderStore: NativeProviderStore;
  applicationInteractions: ApplicationInteractionService;
  spatial: SpatialInteractionService;
  spatialStore: SpatialStore;
  voice: VoiceRuntimeService;
  voiceStore: VoiceStore;
  voiceCaptureLease: VoiceCaptureLeaseService;
  activeContext: ActiveContextService;
  intentRecording: IntentRecordingService;
  intentRecordingStore: IntentRecordingStore;
  semantic: SemanticRetrievalService;
  semanticStore: SemanticRetrievalStore;
  humanUnderstanding: HumanUnderstandingService;
  humanUnderstandingStore: HumanUnderstandingStore;
  knowledgeGraph: PersonalKnowledgeGraphService;
  knowledgeGraphStore: KnowledgeGraphStore;
  learningEngine: LearningEngineService;
  learningEngineStore: LearningEngineStore;
  memoryStudio: CognitiveQueryService;
  memoryStudioStore: MemoryStudioStore;
  localAI: LocalAIService;
  aiRuntime: AIRuntimeService;
  aiRouter: AIRouterService;
  aiEconomics: AIEconomicsService;
  cognitiveContext: CognitiveContextService;
  benchmarkRunner: AIBenchmarkRunner;
  executive: ExecutiveBrainService;
  executiveStore: ExecutiveStore;
  objectives: ObjectiveEngineService;
  experiments: ExperimentService;
  businessOS: BusinessOSService;
  reflection: ReflectionEngineService;
  reflectionStore: ReflectionStore;
  skillEvolution: SkillEvolutionService;
  skillEvolutionStore: SkillEvolutionStore;
  capabilityStudio: CapabilityStudioService;
  capabilityStudioStore: CapabilityStudioStore;
  serverExecutionSigner?: ServerExecutionSigner;
  readOnlyExecutionEnabled: boolean;
}
