import { z } from "zod";

export const CapabilitySchema = z.enum([
  "app.open",
  "app.focus",
  "app.inspect_window",
  "app.capture_window",
  "app.automate",
  "workspace.read",
  "repository.index",
  "repository.initialize_project",
  "repository.inspect",
  "repository.search",
  "repository.file_read",
  "repository.file_create",
  "repository.file_patch",
  "repository.file_delete",
  "repository.git_status",
  "repository.git_diff",
  "repository.integration_diff",
  "repository.git_log",
  "repository.worktree_create",
  "repository.worktree_inspect",
  "repository.worktree_remove",
  "repository.command_run",
  "repository.validate",
  "repository.prepare_commit",
  "repository.integrate_commit",
  "repository.resolve_additive_docs_conflict",
  "repository.merge_candidate",
  "repository.install_dependencies",
  "repository.add_dependency",
  "repository.remove_dependency",
  "repository.dev_server_start",
  "repository.dev_server_status",
  "repository.dev_server_stop",
  "repository.dev_server_restart",
  "workspace.validate",
  "workspace.write",
  "workspace.create_file",
  "workspace.modify_file",
  "workspace.move_file",
  "workspace.delete_file",
  "terminal.run_registered_script",
  "terminal.run_registered_command",
  "shell.execute_arbitrary",
  "filesystem.read_arbitrary",
  "filesystem.delete_permanently",
  "system.run_sudo",
  "credentials.read",
  "keychain.read",
  "banking.perform_action",
  "authentication_code.read",
  "security.disable_controls",
  "git.status",
  "git.diff",
  "git.create_branch",
  "git.commit",
  "git.push",
  "codex.start_readonly",
  "codex.start_write",
  "browser.navigate",
  "browser.read_page",
  "browser.capture",
  "browser.interact",
  "screen.capture",
  "gesture.detect",
  "gesture.cursor",
  "gesture.assistant_control",
  "email.read",
  "email.draft",
  "email.send",
  "calendar.read",
  "calendar.create",
  "calendar.modify",
  "figma.read",
  "figma.write",
  "security.view",
  "security.modify",
  "device.register",
  "device.revoke",
]);

export type Capability = z.infer<typeof CapabilitySchema>;
export type JsonValue = z.infer<ReturnType<typeof z.json>>;

export const ApplicationCapabilitySchema = z.enum([
  "app.open",
  "app.focus",
  "app.inspect_window",
  "app.capture_window",
  "app.automate",
]);

export type ApplicationCapability = z.infer<typeof ApplicationCapabilitySchema>;
