import {
  ClarificationSessionRecordSchema,
  CommandCenterResponseSchema,
  CommandHistoryRecordSchema,
  CommandMetricRecordSchema,
  CommandRecordSchema,
  CommandSuggestionRecordSchema,
  CommandTemplateRecordSchema,
  ExecutionPlanRecordSchema,
  ExecutionStepRecordSchema,
  IntentAnalysisRecordSchema,
  MacroRecordSchema,
  MacroRequestSchema,
  SaveCommandRequestSchema,
  SavedCommandRecordSchema,
  SubmitCommandRequestSchema,
  SubmitCommandResponseSchema,
  type CommandSafetyLevel,
  type IntentAnalysisRecord,
  type IntentCategory,
  type MemoryEvidence,
} from "@alexa-control/shared";

import type { GovernanceAuditWriter } from "../governance/approval-service.js";
import type { AgentSocietyService } from "../agent-society/service.js";
import type { IntentStore } from "./store.js";

const evidenceFor = (at: string, reference: string): MemoryEvidence[] => [
  {
    sourceType: "manual",
    reference,
    excerpt:
      "Generated by the Intent & Execution Engine from an owner command. Planning is governed and does not bypass approval.",
    observedAt: at,
  },
];

const includesAny = (value: string, words: string[]) =>
  words.some((word) => value.includes(word));

export class IntentExecutionService {
  constructor(
    readonly store: IntentStore,
    readonly society: AgentSocietyService,
    readonly audit: GovernanceAuditWriter,
    readonly now: () => Date = () => new Date(),
  ) {}

  async dashboard(ownerId: string) {
    await this.ensureBaseline(ownerId);
    return CommandCenterResponseSchema.parse({
      commands: await this.store.listCommands(ownerId, 200),
      intentAnalyses: await this.store.listIntents(ownerId, 200),
      plans: await this.store.listPlans(ownerId, 200),
      steps: await this.store.listSteps(ownerId, 500),
      history: await this.store.listHistory(ownerId, 200),
      macros: await this.store.listMacros(ownerId),
      savedCommands: await this.store.listSavedCommands(ownerId),
      templates: await this.store.listTemplates(ownerId),
      clarificationSessions: await this.store.listClarifications(ownerId, 100),
      metrics: await this.store.listMetrics(ownerId, 200),
      suggestions: await this.store.listSuggestions(ownerId, 200),
      universalEntryPoint: true,
      bypassesGovernance: false,
    });
  }

  async submit(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    await this.ensureBaseline(input.ownerId, input.requestId);
    const parsed = SubmitCommandRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const intents = this.analyseRequest(input.ownerId, parsed.request, at);
    const safetyLevel = this.safetyFor(intents, parsed.request);
    const approvalRequired = ["moderate_risk", "high_risk", "critical"].includes(
      safetyLevel,
    );
    const commandId = crypto.randomUUID();
    const command = CommandRecordSchema.parse({
      id: commandId,
      ownerId: input.ownerId,
      source: parsed.source,
      originalRequest: parsed.request,
      status: intents.some((intent) => intent.clarificationNeeded)
        ? "needs_clarification"
        : approvalRequired
          ? "waiting_approval"
          : "planned",
      safetyLevel,
      approvalRequired,
      recentAuthenticationRequired:
        safetyLevel === "critical" || safetyLevel === "high_risk",
      privateNetworkRequired: safetyLevel !== "informational",
      trustedDeviceRequired: [
        "read_only",
        "low_risk",
        "moderate_risk",
        "high_risk",
        "critical",
      ].includes(safetyLevel),
      intentIds: intents.map((intent) => intent.id),
      command: {
        action: intents[0]?.primaryGoal ?? parsed.request,
        target: this.targetFor(parsed.request),
        context: { source: parsed.source },
        constraints: [
          "Respect policy and approval boundaries.",
          "Route execution through existing infrastructure only.",
        ],
        priority: intents[0]?.priority ?? "normal",
        approvalLevel: approvalRequired
          ? safetyLevel === "high_risk" || safetyLevel === "critical"
            ? "recent_authentication"
            : "explicit"
          : "none",
        expectedResult: intents[0]?.expectedOutput ?? "Structured command plan.",
        dependencies: [],
        retryPolicy: { maxRetries: 0, strategy: "none" },
      },
      createdAt: at,
      updatedAt: at,
    });
    const planId = crypto.randomUUID();
    const steps = this.stepsFor(command, intents, planId);
    const plan = ExecutionPlanRecordSchema.parse({
      id: planId,
      ownerId: input.ownerId,
      commandId: command.id,
      goal: intents[0]?.primaryGoal ?? parsed.request,
      summary:
        "Inspectable execution plan generated from natural language. Actual execution remains policy-controlled and approval-gated.",
      orderedStepIds: steps.map((step) => step.id),
      parallelGroups: [],
      estimatedDurationSeconds: steps.length * 120,
      approvalsRequired: approvalRequired
        ? [command.command.approvalLevel, "policy_evaluation"]
        : [],
      rollbackStrategy:
        "No irreversible action is performed by command parsing. Future execution must use existing rollback-capable workflows where applicable.",
      validationStrategy:
        "Validate through existing workflow, patch, validation, or read-only execution systems depending on approved step provider.",
      completionCriteria: intents
        .flatMap((intent) => intent.successCriteria)
        .slice(0, 20),
      status:
        command.status === "needs_clarification"
          ? "draft"
          : command.status === "waiting_approval"
            ? "waiting_approval"
            : "ready",
      inspectable: true,
      createdAt: at,
      updatedAt: at,
    });
    const history = CommandHistoryRecordSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      commandId: command.id,
      originalRequest: parsed.request,
      outcome: command.status === "waiting_approval" ? "needs_approval" : "pending",
      durationSeconds: 0,
      agentsInvolved: steps.flatMap((step) => step.assignedAgentIds),
      approvals: plan.approvalsRequired,
      lessonsLearned: [
        "Natural-language command converted to an inspectable governed plan.",
      ],
      createdAt: at,
    });
    for (const intent of intents) await this.store.saveIntent(intent);
    await this.store.saveCommand(command);
    await this.store.savePlan(plan);
    for (const step of steps) await this.store.saveStep(step);
    await this.store.saveHistory(history);
    if (command.status === "needs_clarification") {
      await this.store.saveClarification(
        ClarificationSessionRecordSchema.parse({
          id: crypto.randomUUID(),
          ownerId: input.ownerId,
          commandId: command.id,
          questions: intents
            .flatMap((intent) => intent.clarificationQuestions)
            .slice(0, 5),
          status: "open",
          createdAt: at,
          updatedAt: at,
        }),
      );
    }
    if (this.shouldFormSocietyTeam(intents)) {
      await this.society.formTeam({
        ownerId: input.ownerId,
        body: { goal: plan.goal, repositoryIds: [] },
        requestId: input.requestId,
        ipAddress: input.ipAddress,
      });
    }
    await this.audit({
      eventType: "COMMAND_RECEIVED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Natural-language command parsed into a governed internal command.",
      metadata: { commandId: command.id, safetyLevel, approvalRequired },
      requestId: input.requestId,
    });
    await this.audit({
      eventType: "INTENT_ANALYSED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Intent analysis completed.",
      metadata: { commandId: command.id, intentCount: intents.length },
      requestId: input.requestId,
    });
    await this.audit({
      eventType: approvalRequired
        ? "COMMAND_APPROVAL_REQUIRED"
        : "EXECUTION_PLAN_CREATED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: approvalRequired
        ? "Command requires approval before execution."
        : "Inspectable execution plan created.",
      metadata: { commandId: command.id, planId: plan.id },
      requestId: input.requestId,
    });
    return SubmitCommandResponseSchema.parse({
      command,
      intents,
      plan,
      steps,
      history,
    });
  }

  async saveCommand(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    await this.ensureBaseline(input.ownerId, input.requestId);
    const parsed = SaveCommandRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const saved = SavedCommandRecordSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      name: parsed.name,
      requestTemplate: parsed.requestTemplate,
      pinned: parsed.pinned,
      favorite: parsed.favorite,
      version: "1.0.0",
      createdAt: at,
      updatedAt: at,
    });
    await this.store.saveSavedCommand(saved);
    await this.audit({
      eventType: "COMMAND_SAVED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Reusable command saved.",
      metadata: { savedCommandId: saved.id },
      requestId: input.requestId,
    });
    return saved;
  }

  async createMacro(input: {
    ownerId: string;
    body: unknown;
    requestId: string;
    ipAddress: string;
  }) {
    await this.ensureBaseline(input.ownerId, input.requestId);
    const parsed = MacroRequestSchema.parse(input.body);
    const at = this.now().toISOString();
    const macro = MacroRecordSchema.parse({
      id: crypto.randomUUID(),
      ownerId: input.ownerId,
      name: parsed.name,
      description: parsed.description,
      commandTemplateIds: parsed.commandTemplateIds,
      mode: parsed.mode,
      createdAt: at,
      updatedAt: at,
    });
    await this.store.saveMacro(macro);
    await this.audit({
      eventType: "COMMAND_MACRO_CREATED",
      ownerId: input.ownerId,
      ipAddress: input.ipAddress,
      outcome: "SUCCESS",
      reason: "Command macro created.",
      metadata: { macroId: macro.id, mode: macro.mode },
      requestId: input.requestId,
    });
    return macro;
  }

  async ensureBaseline(ownerId: string, requestId = "system") {
    if ((await this.store.listTemplates(ownerId)).length === 0) {
      const at = this.now().toISOString();
      for (const [name, category, template] of [
        [
          "Morning Startup",
          "productivity",
          "Summarize priorities, check calendar, and show current workflows.",
        ],
        [
          "Repository Review",
          "software_development",
          "Analyze this repository, summarize risks, and propose next steps.",
        ],
        [
          "Security Review",
          "planning",
          "Review the current plan for security, approval, and rollback concerns.",
        ],
      ] as const) {
        await this.store.saveTemplate(
          CommandTemplateRecordSchema.parse({
            id: crypto.randomUUID(),
            ownerId,
            name,
            category,
            template,
            version: "1.0.0",
            createdAt: at,
            updatedAt: at,
          }),
        );
      }
      await this.store.saveMetric(
        CommandMetricRecordSchema.parse({
          id: crypto.randomUUID(),
          ownerId,
          metricName: "command_readiness",
          value: 0.8,
          trend: 0,
          summary: "Command engine can parse, classify, plan, and persist commands.",
          measuredAt: at,
        }),
      );
      await this.store.saveSuggestion(
        CommandSuggestionRecordSchema.parse({
          id: crypto.randomUUID(),
          ownerId,
          title: "Save a repository review command",
          rationale:
            "Repository review commands are likely to recur and can become a pinned reusable template.",
          suggestedCommand:
            "Review this repository and summarize risks, tests, and next steps.",
          confidence: 0.74,
          evidence: evidenceFor(at, "Command baseline suggestion"),
          createdAt: at,
        }),
      );
      await this.audit({
        eventType: "COMMAND_SUGGESTION_CREATED",
        ownerId,
        ipAddress: "system",
        outcome: "SUCCESS",
        reason: "Baseline command suggestions initialized.",
        metadata: { automaticExecution: false },
        requestId,
      });
    }
  }

  private analyseRequest(
    ownerId: string,
    request: string,
    at: string,
  ): IntentAnalysisRecord[] {
    const parts = request
      .split(/\b(?:and then|then|and)\b/i)
      .map((part) => part.trim())
      .filter(Boolean)
      .slice(0, 8);
    return (parts.length ? parts : [request]).map((part) => {
      const normalized = part.toLowerCase();
      const category = this.categoryFor(normalized);
      const clarificationNeeded =
        /\b(that|it|one|previous|yesterday)\b/i.test(part) && part.length < 80;
      return IntentAnalysisRecordSchema.parse({
        id: crypto.randomUUID(),
        ownerId,
        originalRequest: part,
        primaryGoal: this.goalFor(part),
        secondaryGoals: this.secondaryGoalsFor(normalized),
        category,
        contextSummary:
          "Derived from the current command request and owner-scoped platform context.",
        constraints: ["Preserve existing governance.", "Do not bypass approvals."],
        priority: /urgent|asap|now|immediately/i.test(part) ? "urgent" : "normal",
        urgency: /tomorrow|today|deadline/i.test(part) ? "time_sensitive" : "normal",
        requiredPermissions: this.permissionsFor(category),
        requiredCapabilities: this.capabilitiesFor(category, normalized),
        expectedOutput: this.outputFor(category),
        successCriteria: [
          "Intent is represented as a structured command.",
          "Execution plan is inspectable.",
        ],
        confidence: clarificationNeeded ? 0.45 : 0.78,
        clarificationNeeded,
        clarificationQuestions: clarificationNeeded
          ? ["Which specific target should this command use?"]
          : [],
        evidence: evidenceFor(at, part),
        createdAt: at,
      });
    });
  }

  private categoryFor(value: string): IntentCategory {
    if (includesAny(value, ["git", "commit", "branch", "pull", "repo"]))
      return "repository_operations";
    if (includesAny(value, ["code", "test", "build", "bug", "react", "api"]))
      return "software_development";
    if (includesAny(value, ["open", "focus", "launch", "app"]))
      return "application_control";
    if (includesAny(value, ["email", "slack", "message", "notify"]))
      return "communication";
    if (includesAny(value, ["calendar", "meeting"])) return "calendar";
    if (includesAny(value, ["research", "find", "search"])) return "research";
    if (includesAny(value, ["monitor", "watch", "health"])) return "monitoring";
    if (includesAny(value, ["file", "folder", "delete", "move"]))
      return "file_management";
    return "planning";
  }

  private safetyFor(
    intents: IntentAnalysisRecord[],
    request: string,
  ): CommandSafetyLevel {
    const value = request.toLowerCase();
    if (includesAny(value, ["delete", "payment", "bank", "sudo", "admin"]))
      return "critical";
    if (includesAny(value, ["deploy", "send", "email", "push", "merge", "write"]))
      return "high_risk";
    if (intents.some((intent) => intent.category === "repository_operations"))
      return "moderate_risk";
    if (
      intents.some(
        (intent) =>
          intent.category === "knowledge_retrieval" || intent.category === "research",
      )
    )
      return "read_only";
    return "low_risk";
  }

  private stepsFor(
    command: { id: string; ownerId: string; approvalRequired: boolean },
    intents: IntentAnalysisRecord[],
    planId: string,
  ) {
    const agentsByCapability = (capability: string) =>
      capability.includes("security")
        ? ["security_agent"]
        : capability.includes("test")
          ? ["testing_agent"]
          : ["planning_agent"];
    return intents.map((intent, index) =>
      ExecutionStepRecordSchema.parse({
        id: crypto.randomUUID(),
        ownerId: command.ownerId,
        planId,
        commandId: command.id,
        sequence: index + 1,
        title: intent.primaryGoal,
        description: `Resolve ${intent.category} intent through the governed execution router.`,
        assignedAgentIds: [
          ...new Set(intent.requiredCapabilities.flatMap(agentsByCapability)),
        ],
        requiredCapabilities: intent.requiredCapabilities,
        executionProvider: this.providerFor(intent.category),
        approvalRequired: command.approvalRequired,
        status: command.approvalRequired ? "waiting_approval" : "ready",
        startedAt: null,
        completedAt: null,
      }),
    );
  }

  private providerFor(category: IntentCategory) {
    if (category === "software_development") return "workflow_engine";
    if (category === "repository_operations") return "read_only_execution";
    if (category === "integrations" || category === "communication")
      return "integration_registry";
    if (category === "planning" || category === "research") return "agent_society";
    return "manual_owner";
  }

  private goalFor(part: string) {
    return (
      part
        .replace(/[.!?]+$/g, "")
        .slice(0, 1)
        .toUpperCase() + part.replace(/[.!?]+$/g, "").slice(1)
    );
  }
  private targetFor(request: string) {
    return (
      request.match(/\b(repo|repository|app|file|dashboard|api|agent)\b/i)?.[0] ??
      "assistant"
    );
  }
  private secondaryGoalsFor(value: string) {
    return includesAny(value, ["summarize", "summary"]) ? ["Summarize result"] : [];
  }
  private permissionsFor(category: IntentCategory) {
    if (category === "application_control") return ["application_control_policy"];
    if (category === "repository_operations")
      return ["registered_workspace", "read_only_execution"];
    if (category === "communication") return ["integration_permission"];
    return ["owner_session"];
  }
  private capabilitiesFor(category: IntentCategory, value: string) {
    const base =
      category === "software_development"
        ? ["planning", "repository_intelligence", "testing"]
        : [category];
    return includesAny(value, ["security", "auth"]) ? [...base, "security"] : base;
  }
  private outputFor(category: IntentCategory) {
    return category === "software_development"
      ? "Implementation or validation plan."
      : "Completed governed command plan.";
  }
  private shouldFormSocietyTeam(intents: IntentAnalysisRecord[]) {
    return intents.some((intent) =>
      ["software_development", "planning", "repository_operations"].includes(
        intent.category,
      ),
    );
  }
}
